name: pattern-recognition-env
channels:
  - defaults
dependencies:
  - flake8=7.3.0
  - pip=25.3
  - pytest=8.4.2
  - python=3.12.12
  - pip:
      - loguru==0.7.3
      - matplotlib==3.10.8
      - numpy==2.3.5
      - pandas==2.3.3
      - pillow==12.0.0
      - scikit-learn==1.8.0
      - seaborn==0.13.2
      - torch==2.9.1+cu126
      - torchvision==0.24.1+cu126
      - triton==3.5.1
